#!/bin/sh
# repurposeaswan.sh — Set up an interface as a DHCP WAN + watchdog
# Usage: repurposeaswan.sh <interface>
#
# Runs as a daemon; write PID to /tmp/repurpose_<iface>.pid.
# Watchdog loop (every 15s) checks:
#   1. br0 re-binding (fixes it immediately if detected)
#   2. Interface UP state
#   3. udhcpc still alive
# Exits cleanly when /tmp/repurpose_active is removed or changed.

if [ -z "$1" ]; then
    echo "Usage: $0 <interface>" >&2
    exit 1
fi

TARGET_IFACE="$1"
SCRIPT_PATH="/tmp/udhcpc_${TARGET_IFACE}.script"
STATE_FILE="/tmp/repurpose_active"
PID_FILE="/tmp/repurpose_${TARGET_IFACE}.pid"
UDHCPC_PID="/var/run/udhcpc.${TARGET_IFACE}.pid"
LOG="/tmp/repurpose_${TARGET_IFACE}.log"
WATCHDOG_INTERVAL=15

# ── Write PID + state immediately ─────────────────────────────────────────────
echo $$ > "$PID_FILE"
printf '%s' "$TARGET_IFACE" > "$STATE_FILE"
printf '[%s] repurposeaswan started  iface=%s  pid=%s\n' \
    "$(busybox date)" "$TARGET_IFACE" "$$" > "$LOG"

# ── Create the udhcpc handler (single-quoted heredoc — no expansion) ──────────
busybox cat > "$SCRIPT_PATH" << 'UDHCPC_HANDLER_EOF'
#!/bin/sh
# udhcpc handler — generated by repurposeaswan.sh
case "$1" in
    deconfig)
        ip addr flush dev "$interface" 2>/dev/null
        ;;
    bound|renew)
        ip addr flush dev "$interface" 2>/dev/null
        # $subnet is dotted-decimal (e.g. 255.255.255.0); ip(8) accepts it.
        # Fall back to /24 only when udhcpc leaves $subnet empty.
        ip addr add "$ip/${subnet:-24}" dev "$interface" 2>/dev/null
        if [ -n "$router" ]; then
            ip route del default dev "$interface" 2>/dev/null
            ip route add default via "$router" dev "$interface" 2>/dev/null
            # Persist gateway so the watchdog can restore it if the route is stolen
            printf '%s' "$router" > "/tmp/repurpose_gw_${interface}"
            # Idempotent: delete first, then add, so repeated renewals don't stack rules
            iptables -t nat -D POSTROUTING -o "$interface" -j MASQUERADE 2>/dev/null
            iptables -t nat -A POSTROUTING -o "$interface" -j MASQUERADE 2>/dev/null
        fi
        ;;
esac
exit 0
UDHCPC_HANDLER_EOF
busybox chmod +x "$SCRIPT_PATH"

# ── Helper: true if $TARGET_IFACE is currently enslaved to br0 ────────────────
_in_br0() {
    _M=$(ip link show "$TARGET_IFACE" 2>/dev/null \
        | busybox sed -n 's/.* master \([^ ]*\) .*/\1/p' \
        | busybox tr -d '\r\n')
    [ "$_M" = "br0" ]
}

# ── Helper: remove from br0 if enslaved; log the fix ─────────────────────────
# Returns 0 (success) if a fix was applied, 1 if nothing to do.
_fix_br0() {
    if _in_br0; then
        ip link set "$TARGET_IFACE" nomaster 2>/dev/null
        ip link set "$TARGET_IFACE" up 2>/dev/null
        printf '[%s] FIXED br0 re-enslavement — removed %s from br0 + brought UP\n' \
            "$(busybox date)" "$TARGET_IFACE" >> "$LOG"
        return 0
    fi
    return 1
}

# ── Helper: resolve the /24 subnet TARGET_IFACE is currently on ──────────────
# Mirrors lmehspt.sh's resolve_br0_gateway() logic (assume /24, take the
# interface's own IPv4 and zero the last octet) so the repurposed-WAN's own
# local network (e.g. 192.168.69.0/24) can be blocked for hotspot clients,
# the same way br0's subnet is blocked. Echoes nothing if no IPv4 yet.
_resolve_iface_subnet() {
    local _rif="$1" _rip
    _rip=$(ip -4 addr show "$_rif" 2>/dev/null | busybox grep -o 'inet [0-9.]*' | busybox awk '{print $2}' | head -1)
    if [ -z "$_rip" ]; then
        _rip=$(ifconfig "$_rif" 2>/dev/null | busybox grep -o 'inet \(addr:\)\?[0-9.]*' | busybox grep -o '[0-9.]*' | head -1)
    fi
    [ -n "$_rip" ] && printf '%s' "$_rip" | busybox sed 's/\.[^.]*$/.0\/24/'
}

# ── Helper: current hotspot bridge name (falls back to "br1") ────────────────
_hotspot_br() {
    _hb=$(grep -m1 '^HOTSPOT_BR=' /tmp/coin_config.env 2>/dev/null \
        | sed 's/^HOTSPOT_BR="//;s/"$//')
    printf '%s' "${_hb:-br1}"
}

# ── Helper: true if TARGET_IFACE is a wlan*-vxd that is disabled in the MIB ──
# VXD interfaces live at slot 5 of their radio's MBSSIB table:
#   wlan0-vxd → WLAN_MBSSIB_TBL.5.wlanDisabled
#   wlan1-vxd → WLAN1_MBSSIB_TBL.5.wlanDisabled
# Non-VXD interfaces (LAN ports, main wlan0/wlan1) always return false —
# they have no per-MBSSIB slot 5 disable bit owned by wlanbasic.cgi.
_vxd_mib_disabled() {
    local _tbl
    case "$TARGET_IFACE" in
        wlan0-vxd) _tbl="WLAN_MBSSIB_TBL"  ;;
        wlan1-vxd) _tbl="WLAN1_MBSSIB_TBL" ;;
        *)          return 1                  ;;
    esac
    _VD=$(mib get "${_tbl}.5.wlanDisabled" 2>/dev/null \
        | busybox grep '=' \
        | busybox cut -d'=' -f2- \
        | busybox tr -d '\r\n')
    [ "${_VD:-0}" = "1" ]
}

# ── Helper: true if our udhcpc PID is alive ───────────────────────────────────
_udhcpc_alive() {
    if [ -f "$UDHCPC_PID" ]; then
        _UP=$(busybox tr -d '\r\n' < "$UDHCPC_PID" 2>/dev/null)
        [ -n "$_UP" ] && kill -0 "$_UP" 2>/dev/null && return 0
    fi
    # Fallback: process name scan
    busybox ps 2>/dev/null \
        | busybox grep "udhcpc" \
        | busybox grep -q "$TARGET_IFACE"
}

# ── Helper: start (or restart) udhcpc ────────────────────────────────────────
# Kills any existing instance for this interface first so we never end up
# with two udhcpc processes racing each other on the same interface (the old
# behaviour was to start a second one on top of the still-running one).
_start_udhcpc() {
    if [ -f "$UDHCPC_PID" ]; then
        _SU_OLD=$(busybox tr -d '\r\n' < "$UDHCPC_PID" 2>/dev/null)
        [ -n "$_SU_OLD" ] && kill "$_SU_OLD" 2>/dev/null
    fi
    busybox sleep 1   # let it die before we grab the PID file
    busybox udhcpc \
        -i "$TARGET_IFACE" \
        -s "$SCRIPT_PATH" \
        -b \
        -p "$UDHCPC_PID" \
        2>/dev/null
    printf '[%s] udhcpc (re)started for %s\n' \
        "$(busybox date)" "$TARGET_IFACE" >> "$LOG"
}

# ── Helper: force a DHCP rediscover after a carrier/br0 event ────────────────
# Called when the watchdog detects the cable was just plugged in (carrier 0→1)
# or that the vendor daemon re-enslaved the interface to br0 (and we just freed
# it). In both cases udhcpc is likely still alive but stuck in background-retry
# mode with a long inter-attempt gap, so it won't discover on its own for a
# long time. We flush stale addresses and start a fresh instance immediately.
_kick_udhcpc() {
    ip addr flush dev "$TARGET_IFACE" 2>/dev/null
    _start_udhcpc
    printf '[%s] KICK: udhcpc restarted for %s (br0/carrier event)\n' \
        "$(busybox date)" "$TARGET_IFACE" >> "$LOG"
}

# ── Helper: wait for target interface to be ready ────────────────────────────
_wait_for_interface_ready() {
    local max_wait=90 waited=0
    # Define your bridge name here (br0 or br1)
    local target_bridge="br0" 

    # Stage 1: Wait for the interface to exist in the filesystem
    while [ $waited -lt $max_wait ]; do
        [ -e "/sys/class/net/$TARGET_IFACE" ] && break
        busybox sleep 1
        waited=$((waited + 1))
    done

    # Stage 2: Wait for it to be bound to the bridge
    waited=0
    while [ $waited -lt $max_wait ]; do
        # Replaced hardcoded wlan0 with $TARGET_IFACE
        [ -e "/sys/class/net/$target_bridge/brif/$TARGET_IFACE" ] && break
        busybox sleep 1
        waited=$((waited + 1))
    done
    
    # Settle delay
    busybox sleep 3
}

# ── Initial setup ──────────────────────────────────────────────────────────────
printf '[%s] Waiting for interface %s to become ready...\n' \
    "$(busybox date)" "$TARGET_IFACE" >> "$LOG"

_wait_for_interface_ready

printf '[%s] Interface %s ready. Initial setup: nomaster → up → udhcpc\n' \
    "$(busybox date)" "$TARGET_IFACE" >> "$LOG"

ip link set "$TARGET_IFACE" nomaster 2>/dev/null
ip link set "$TARGET_IFACE" up
_start_udhcpc

# ── LAN isolation ──────────────────────────────────────────────────────────
# Block the device on this repurposed WAN port from reaching any br0 LAN
# device. www2 (port 8080) listens on 0.0.0.0 and is hit via INPUT, so no
# FORWARD exception is needed — the admin UI remains reachable.
# Honour the LAN_ISOLATE toggle from coin_config.env (default: on).
_LAN_ISOLATE=$(grep -m1 '^LAN_ISOLATE=' /tmp/coin_config.env 2>/dev/null \
    | sed 's/^LAN_ISOLATE="//;s/"$//')
if [ "${_LAN_ISOLATE:-1}" = "1" ]; then
    iptables -t filter -D FORWARD -i "$TARGET_IFACE" -o br0 -j DROP 2>/dev/null
    iptables -t filter -I FORWARD 1 -i "$TARGET_IFACE" -o br0 -j DROP
    iptables -t filter -D INPUT -i "$TARGET_IFACE" -p tcp --dport 8080 -j ACCEPT 2>/dev/null
    iptables -t filter -I INPUT 1 -i "$TARGET_IFACE" -p tcp --dport 8080 -j ACCEPT
    # Block hotspot clients from reaching the repurposed-WAN's own upstream
    # subnet directly (its gateway + sibling devices, e.g. 192.168.69.0/24).
    # The rule above only stops that network from reaching INTO br0 — it does
    # nothing to stop br1 clients from addressing that subnet themselves,
    # since their traffic egresses via TARGET_IFACE, not br0. Destination-based
    # so ordinary internet-bound traffic (routed *through* the gateway, not
    # *to* it) is unaffected.
    _RPW_HOTSPOT_BR=$(_hotspot_br)
    _RPW_SUBNET=$(_resolve_iface_subnet "$TARGET_IFACE")
    if [ -n "$_RPW_SUBNET" ]; then
        iptables -t filter -D FORWARD -i "$_RPW_HOTSPOT_BR" -d "$_RPW_SUBNET" -j DROP 2>/dev/null
        iptables -t filter -I FORWARD 1 -i "$_RPW_HOTSPOT_BR" -d "$_RPW_SUBNET" -j DROP
        printf '%s\n' "$_RPW_SUBNET" > "/tmp/repurpose_subnet_${TARGET_IFACE}.mark"
    fi
    printf '[%s] LAN isolation rules applied for %s\n' \
        "$(busybox date)" "$TARGET_IFACE" >> "$LOG"
fi
# ──────────────────────────────────────────────────────────────────────────

printf '[%s] Setup complete — watchdog interval=%ds\n' \
    "$(busybox date)" "$WATCHDOG_INTERVAL" >> "$LOG"

# Seed carrier baseline so the watchdog can detect 0→1 transitions.
# Read after initial setup: if cable is already connected at this point
# the watchdog won't fire a spurious kick on the very first tick.
_LAST_CARRIER=$(busybox cat "/sys/class/net/$TARGET_IFACE/carrier" 2>/dev/null | busybox tr -d '\r\n')
_LAST_CARRIER="${_LAST_CARRIER:-0}"

# ── Watchdog loop ──────────────────────────────────────────────────────────────
while true; do
    busybox sleep "$WATCHDOG_INTERVAL"

    # ── Exit condition: state file gone or points to a different iface ────────
    if [ ! -f "$STATE_FILE" ]; then
        printf '[%s] State file removed — exiting\n' \
            "$(busybox date)" >> "$LOG"
        rm -f "$PID_FILE"
        exit 0
    fi
    _CUR=$(busybox tr -d '\r\n' < "$STATE_FILE" 2>/dev/null)
    if [ "$_CUR" != "$TARGET_IFACE" ]; then
        printf '[%s] State changed to "%s" — exiting\n' \
            "$(busybox date)" "$_CUR" >> "$LOG"
        rm -f "$PID_FILE"
        exit 0
    fi

    # ── VXD MIB disable check ─────────────────────────────────────────────────
    # When the user disables a wlan*-vxd interface via wlanbasic.cgi, it sets
    # WLAN*_MBSSIB_TBL.5.wlanDisabled=1 and calls wlan_apply, which instructs
    # the driver to bring the VXD kernel interface down.  Without this check the
    # watchdog would detect the DOWN state at check 2 and fight the driver by
    # immediately forcing it UP again — every 15 seconds, indefinitely.
    # Read the authoritative MIB bit so the decision is not affected by
    # transient kernel interface states.
    if _vxd_mib_disabled; then
        printf '[%s] %s: wlanDisabled=1 in MIB — stopping repurpose watchdog\n' \
            "$(busybox date)" "$TARGET_IFACE" >> "$LOG"
        rm -f "$STATE_FILE" "$PID_FILE"
        exit 0
    fi

    # ── 1. br0 binding check (highest priority) ───────────────────────────────
    # _fix_br0 returns 0 when it actually had to remove the interface from br0
    # (vendor networking daemon re-enslaved it on link-up — the main reason
    # plugging in a cable after setup failed to obtain an IP).  On that event
    # kick udhcpc immediately; don't wait for the liveness check below, because
    # udhcpc is still alive — just silently stuck in background-retry mode.
    _kicked_this_tick=0
    if _fix_br0; then
        _kick_udhcpc
        _kicked_this_tick=1
    fi

    # ── 2. Interface UP check ─────────────────────────────────────────────────
    _S=$(ip link show "$TARGET_IFACE" 2>/dev/null \
        | busybox grep -o "state [A-Z]*" \
        | busybox awk '{print $2}' \
        | head -1)
    if [ "$_S" != "UP" ]; then
        ip link set "$TARGET_IFACE" up 2>/dev/null
        printf '[%s] Interface %s was %s — brought back UP\n' \
            "$(busybox date)" "$TARGET_IFACE" "${_S:-UNKNOWN}" >> "$LOG"
    fi

    # ── 3. udhcpc liveness check ──────────────────────────────────────────────
    if ! _udhcpc_alive; then
        printf '[%s] udhcpc died — restarting\n' \
            "$(busybox date)" >> "$LOG"
        _start_udhcpc
        _kicked_this_tick=1
    fi

    # ── 4. Default route maintenance ──────────────────────────────────────────
    # If the system (vendor firmware, nas* interface, etc.) steals the default
    # route away from our repurposed WAN, restore it from the saved gw file.
    _GW_FILE="/tmp/repurpose_gw_${TARGET_IFACE}"
    if [ -f "$_GW_FILE" ]; then
        _GW=$(busybox tr -d '\r\n' < "$_GW_FILE" 2>/dev/null)
        if [ -n "$_GW" ]; then
            _CUR=$(ip route show default 2>/dev/null | head -1)
            case "$_CUR" in
                *"dev $TARGET_IFACE"*) ;; # already correct
                *)
                    ip route del default 2>/dev/null
                    ip route add default via "$_GW" dev "$TARGET_IFACE" 2>/dev/null
                    printf '[%s] RESTORED default route via %s dev %s\n' \
                        "$(busybox date)" "$_GW" "$TARGET_IFACE" >> "$LOG"
                    ;;
            esac
        fi
    fi

    # ── 5. LAN isolation watchdog — honour LAN_ISOLATE toggle ────────────────
    _LI=$(grep -m1 '^LAN_ISOLATE=' /tmp/coin_config.env 2>/dev/null \
        | sed 's/^LAN_ISOLATE="//;s/"$//')
    _RPW_MARK="/tmp/repurpose_subnet_${TARGET_IFACE}.mark"
    _RPW_OLD_SUBNET=$(busybox cat "$_RPW_MARK" 2>/dev/null)
    if [ "${_LI:-1}" = "1" ]; then
        iptables -t filter -D FORWARD -i "$TARGET_IFACE" -o br0 -j DROP 2>/dev/null
        iptables -t filter -I FORWARD 1 -i "$TARGET_IFACE" -o br0 -j DROP
        _RPW_HOTSPOT_BR=$(_hotspot_br)
        _RPW_SUBNET=$(_resolve_iface_subnet "$TARGET_IFACE")
        if [ -n "$_RPW_OLD_SUBNET" ] && [ "$_RPW_OLD_SUBNET" != "$_RPW_SUBNET" ]; then
            iptables -t filter -D FORWARD -i "$_RPW_HOTSPOT_BR" -d "$_RPW_OLD_SUBNET" -j DROP 2>/dev/null
        fi
        if [ -n "$_RPW_SUBNET" ]; then
            iptables -t filter -D FORWARD -i "$_RPW_HOTSPOT_BR" -d "$_RPW_SUBNET" -j DROP 2>/dev/null
            iptables -t filter -I FORWARD 1 -i "$_RPW_HOTSPOT_BR" -d "$_RPW_SUBNET" -j DROP
            printf '%s\n' "$_RPW_SUBNET" > "$_RPW_MARK"
        else
            rm -f "$_RPW_MARK"
        fi
    else
        iptables -t filter -D FORWARD -i "$TARGET_IFACE" -o br0 -j DROP 2>/dev/null
        [ -n "$_RPW_OLD_SUBNET" ] && iptables -t filter -D FORWARD -i "$(_hotspot_br)" -d "$_RPW_OLD_SUBNET" -j DROP 2>/dev/null
        rm -f "$_RPW_MARK"
    fi
    # ──────────────────────────────────────────────────────────────────────────

    # ── 6. Carrier state tracking (cable plug-in detection) ───────────────────
    # Belt-and-suspenders for cases where the vendor daemon does NOT re-enslave
    # the interface to br0 on link-up (rare but possible — e.g. when a WLAN
    # interface associates with an AP, or when the LAN switchd handles link
    # events without touching br0).  A 0→1 carrier transition that wasn't
    # already handled by the br0 fix above means cable just appeared —
    # kick udhcpc so we get a lease right away instead of waiting for its
    # next background-retry interval (which can be several minutes).
    _CUR_CARRIER=$(busybox cat "/sys/class/net/$TARGET_IFACE/carrier" 2>/dev/null \
        | busybox tr -d '\r\n')
    _CUR_CARRIER="${_CUR_CARRIER:-0}"
    if [ "$_CUR_CARRIER" = "1" ] && [ "$_LAST_CARRIER" = "0" ] \
       && [ "$_kicked_this_tick" = "0" ]; then
        printf '[%s] Carrier came up on %s (no br0 event) — kicking udhcpc\n' \
            "$(busybox date)" "$TARGET_IFACE" >> "$LOG"
        ip link set "$TARGET_IFACE" up 2>/dev/null
        _kick_udhcpc
    fi
    _LAST_CARRIER="$_CUR_CARRIER"
done
